import { defineCollection, z } from 'astro:content';
import { file } from 'astro/loaders';

const pair = z.object({ int: z.string().nullable(), deu: z.string().nullable() });
const gloss = z.object({ de: z.string().nullable(), en: z.string().nullable() });
const gramLabel = z.object({
	code: z.string().nullable(),
	en: z.string().nullable(),
	de: z.string().nullable(),
	deLay: z.string().nullable(),
	roman: z.string().nullable(),
});

// Covers every paradigm.forms shape (single, gendered, exist) — a full discriminated union
// per `kind` would be tidier, but this is a static build-time dataset generated by our own
// pipeline, not user input, so a permissive superset schema is enough to catch real shape
// drift between the pipeline and the site without extra ceremony.
const paradigmForm = z.object({
	label: z.array(z.string().nullable()),
	labelDisplay: z.object({ code: z.string(), de: z.string(), en: z.string() }).optional(),
	int: z.string().nullable().optional(),
	deu: z.string().nullable().optional(),
	intM: z.string().nullable().optional(),
	intF: z.string().nullable().optional(),
	deuM: z.string().nullable().optional(),
	deuF: z.string().nullable().optional(),
	german: z.string().nullable().optional(),
	english: z.string().nullable().optional(),
});

const entrySchema = z.object({
	id: z.string(),
	slug: z.string(),
	lemma: z.object({ int: z.string(), deu: z.string() }),
	composition: pair.nullable(),
	variation: pair.nullable(),
	reconstruction: pair.nullable(),
	source: z.object({
		code: z.string().nullable(),
		isDerivation: z.boolean(),
		label: z.object({ en: z.string().nullable(), de: z.string().nullable() }).nullable(),
		foreignForm: pair.nullable(),
		derivationBase: pair.nullable(),
		derivationSlug: z.string().nullable(),
	}),
	base: z.object({
		int: z.string().nullable(),
		deu: z.string().nullable(),
		slug: z.string().nullable(),
		isSelf: z.boolean(),
		glosses: z.array(gloss),
	}).nullable(),
	wordClass: z.object({ class1: gramLabel, class2: gramLabel }),
	flexion: z.object({
		flexion1: z.string().nullable(),
		flexion2: pair.nullable(),
		flexion3: pair.nullable(),
	}),
	paradigm: z.object({
		kind: z.enum(['none', 'exist', 'gendered', 'noun', 'verb', 'error']),
		key: z.string().nullable(),
		sheetName: z.string().nullable(),
		forms: z.array(paradigmForm),
	}),
	glosses: z.array(gloss),
	domain: z.string().nullable(),
	wordFamily: z.array(z.object({ slug: z.string(), lemma: z.object({ int: z.string(), deu: z.string() }), glosses: z.array(gloss) })),
});

const entries = defineCollection({
	loader: file('src/data/generated/entries.json'),
	schema: entrySchema,
});

export const collections = { entries };
